version: "3.8"
services:
  odd-collector:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: odd-collector
    restart: always
    environment:
      # Cache refreshing interval (minutes):
      - SCHEDULER_INTERVAL_MINUTES=${SCHEDULER_INTERVAL_MINUTES}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - EXCLUDE_TABLES=${EXCLUDE_TABLES}
      # FLASK:
      - FLASK_ENVIRONMENT=${FLASK_ENVIRONMENT}
      - FLASK_APP=${FLASK_APP}
    ports:
      - "127.0.0.1:8080:8080"
